from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from xml.etree import ElementTree

from .models import QualityGate


@dataclass(frozen=True)
class JunitSummary:
    tests: int
    failures: int
    errors: int
    skipped: int
    duration_seconds: float

    @property
    def gate(self) -> QualityGate:
        if self.failures or self.errors:
            return QualityGate.FAIL
        if self.skipped:
            return QualityGate.PASS_WITH_RISK
        return QualityGate.PASS


def parse_junit(path: str | Path) -> JunitSummary:
    root = ElementTree.parse(path).getroot()
    suites = [root] if root.tag == "testsuite" else list(root.findall("testsuite"))

    return JunitSummary(
        tests=sum(int(suite.attrib.get("tests", 0)) for suite in suites),
        failures=sum(int(suite.attrib.get("failures", 0)) for suite in suites),
        errors=sum(int(suite.attrib.get("errors", 0)) for suite in suites),
        skipped=sum(int(suite.attrib.get("skipped", 0)) for suite in suites),
        duration_seconds=sum(float(suite.attrib.get("time", 0)) for suite in suites),
    )


def render_markdown(summary: JunitSummary) -> str:
    return "\n".join(
        [
            "# Test Execution Report",
            "",
            f"**Quality gate:** `{summary.gate}`",
            "",
            "| Metric | Value |",
            "|---|---:|",
            f"| Tests | {summary.tests} |",
            f"| Failures | {summary.failures} |",
            f"| Errors | {summary.errors} |",
            f"| Skipped | {summary.skipped} |",
            f"| Duration | {summary.duration_seconds:.2f}s |",
            "",
            "Generated by `test-workflow report`.",
        ]
    )
