from . import reference as _reference_module
from .canonical import CanonicalizationError, canonical_json_bytes, canonical_sha256
from .models import (
    AccessOperation,
    AclEffect,
    AclEntry,
    AclSubjectType,
    AppendRevisionResult,
    AuditEvent,
    CompatibilityContext,
    CompatibilityDescriptor,
    ConflictArtifact,
    CreatorType,
    Decision,
    EffectiveReadDecision,
    ErrorCode,
    ForgetTombstone,
    LifecycleState,
    MemoryContractError,
    MemoryKind,
    MemoryNamespace,
    MemoryRevision,
    MutationResult,
    NamespaceScopeKind,
    PermissionDecision,
    PrincipalContext,
    PrincipalType,
    PromotionDecision,
    PromotionRequest,
    Provenance,
    ReadMode,
    RetentionPolicy,
    StateEvent,
    TransformationKind,
    TransitionDecision,
)
from .policy import (
    ALLOWED_TRANSITIONS,
    READ_STATES,
    ROLE_PERMISSIONS,
    compatibility_matches,
    evaluate_effective_read,
    evaluate_permission,
    namespace_authorized,
    operation_for_transition,
    validate_promotion,
    validate_transition,
)
from .ports import (
    MemoryAclPort,
    MemoryAuditPort,
    MemoryMaintenancePort,
    MemoryQueryPort,
    MemoryRevisionPort,
    MemoryStatePort,
)
from .reference_hardened import DeterministicMemoryReference

# Preserve the historical submodule import path while routing all package and
# proof consumers through the hardened adapter.
_reference_module.DeterministicMemoryReference = DeterministicMemoryReference

__all__ = [
    "ALLOWED_TRANSITIONS",
    "READ_STATES",
    "ROLE_PERMISSIONS",
    "AccessOperation",
    "AclEffect",
    "AclEntry",
    "AclSubjectType",
    "AppendRevisionResult",
    "AuditEvent",
    "CanonicalizationError",
    "CompatibilityContext",
    "CompatibilityDescriptor",
    "ConflictArtifact",
    "CreatorType",
    "Decision",
    "DeterministicMemoryReference",
    "EffectiveReadDecision",
    "ErrorCode",
    "ForgetTombstone",
    "LifecycleState",
    "MemoryAclPort",
    "MemoryAuditPort",
    "MemoryContractError",
    "MemoryKind",
    "MemoryMaintenancePort",
    "MemoryNamespace",
    "MemoryQueryPort",
    "MemoryRevision",
    "MemoryRevisionPort",
    "MemoryStatePort",
    "MutationResult",
    "NamespaceScopeKind",
    "PermissionDecision",
    "PrincipalContext",
    "PrincipalType",
    "PromotionDecision",
    "PromotionRequest",
    "Provenance",
    "ReadMode",
    "RetentionPolicy",
    "StateEvent",
    "TransformationKind",
    "TransitionDecision",
    "canonical_json_bytes",
    "canonical_sha256",
    "compatibility_matches",
    "evaluate_effective_read",
    "evaluate_permission",
    "namespace_authorized",
    "operation_for_transition",
    "validate_promotion",
    "validate_transition",
]
